---
- hosts: raspbian
  become: true
  become_method: sudo
  roles:
  # - placeholder

  tasks:

    - name: Install base
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      with_items:
        - realvnc-vnc-server
        - realvnc-vnc-viewer
        - vim
      tags:
        - base

    - name: generate /etc/lightdm/lightdm.conf
      template:
        src: lightdm.conf.j2
        dest: /etc/lightdm/lightdm.conf
        owner: root
        group: root
        mode: 0644
      notify: restart lightdm service
      tags:
        - lightdm

    - name: python virtualenv and wrapper
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      with_items:
        - python-virtualenv
        - virtualenvwrapper
      tags:
        - python

    - name: update .bashrc
      lineinfile:
        path: /home/pi/.bashrc
        line: "{{ item }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - export WORKON_HOME=~/.virtualenvs
        - source /usr/local/bin/virtualenvwrapper.sh

  handlers:

    - name: restart lightdm service
      service:
        name: lightdm
        state: restarted
      tags:
        - lightdm
